


#██╗░░░░░░█████╗░██████╗░██████╗░██╗░░░██╗  ███████╗██╗░██████╗░██╗░░██╗████████╗██╗███╗░░██╗░██████╗░
#██║░░░░░██╔══██╗██╔══██╗██╔══██╗╚██╗░██╔╝  ██╔════╝██║██╔════╝░██║░░██║╚══██╔══╝██║████╗░██║██╔════╝░
#██║░░░░░██║░░██║██████╦╝██████╦╝░╚████╔╝░  █████╗░░██║██║░░██╗░███████║░░░██║░░░██║██╔██╗██║██║░░██╗░
#██║░░░░░██║░░██║██╔══██╗██╔══██╗░░╚██╔╝░░  ██╔══╝░░██║██║░░╚██╗██╔══██║░░░██║░░░██║██║╚████║██║░░╚██╗
#███████╗╚█████╔╝██████╦╝██████╦╝░░░██║░░░  ██║░░░░░██║╚██████╔╝██║░░██║░░░██║░░░██║██║░╚███║╚██████╔╝
#╚══════╝░╚════╝░╚═════╝░╚═════╝░░░░╚═╝░░░  ╚═╝░░░░░╚═╝░╚═════╝░╚═╝░░╚═╝░░░╚═╝░░░╚═╝╚═╝░░╚══╝░╚═════╝░
#

#                       ▒█▀▀█ █░░█ 　 ▒█░░░ █░░█ ▀▀█▀▀ █▀▀█ ░▀░ █▀▀█ 
#                       ▒█▀▀▄ █▄▄█ 　 ▒█░░░ █▄▄█ ░░█░░ █▄▄▀ ▀█▀ █▄▄█ 
#                       ▒█▄▄█ ▄▄▄█ 　 ▒█▄▄█ ▄▄▄█ ░░▀░░ ▀░▀▀ ▀▀▀ ▀░░▀
#
#




messages:
  disablingin5: "§cDisabling pvp in §45 §cseconds"
  disablingin4: "§cDisabling pvp in §44 §cseconds"
  disablingin3: "§cDisabling pvp in §43 §cseconds"
  disablingin2: "§cDisabling pvp in §42 §cseconds"
  disablingin1: "§cDisabling pvp in §41 §csecond"
  pvpdisabled: "&c[&4!&c] You disabled pvp !"
  enablingpvp: "&c[&4!&c] You enabled pvp !"
  
  actionbar: "&e&lPvp &6&lEnabled"
  abin5: "&c&lPvp Disabling: &4&l5"
  abin4: "&c&lPvp Disabling: &4&l4"
  abin3: "&c&lPvp Disabling: &4&l3"
  abin2: "&c&lPvp Disabling: &4&l2"
  abin1: "&c&lPvp Disabling: &4&l1"
  abin: "&4&lPvp Disabled !"
  
  #player runs a disabled command in pvp mode
  oncmdinpvp: "&c[&4!&c] You can't execute this command in pvp mode !"
  cancel: "&c[&4!&c] You will no longer disable pvp !"
  cooldown: "§c[§4!§c] You need to wait §4%time% §csecond(s) to execute this command !"
  targetnopvp: "&c[&4!&c] This player does not have pvp enabled."
  playernopvp: "&c[&4!&c] You have pvp disabled !"
  reload: "&c[&4!&c] &aPlugin reloaded"
  noperm: "&c[&4!&c] You don't have permission"
  attacked: "&c[&4!&c] You attacked a player you can't disable pvp now !"
  gotattacked: "&c[&4!&c] You got attacked you can't disable pvp now !"


#               ╭━━╮╭╮        ╭━╮
#               ╰┃┃╯┃╰╮╭━╮╭━━╮┃━┫
#               ╭┃┃╮┃╭┫┃┻┫┃┃┃┃┣━┃
#               ╰━━╯╰━╯╰━╯╰┻┻╯╰━╯
  sword: "&c&lPVP &7[Right-Click]"
  swordlore: ""
  
  redstoneblock: "&c&lDisable &7[Right-Click]"
  redstonelore: ""
  
  
  
  
#            ┏━━━┓                ┏┓
#            ┃┏━┓┃                ┃┃
#            ┃┃ ┗╋━━┳┓┏┳┓┏┳━━┳━┓┏━┛┣━━┓
#            ┃┃ ┏┫┏┓┃┗┛┃┗┛┃┏┓┃┏┓┫┏┓┃━━┫
#            ┃┗━┛┃┗┛┃┃┃┃┃┃┃┏┓┃┃┃┃┗┛┣━━┃
#            ┗━━━┻━━┻┻┻┻┻┻┻┛┗┻┛┗┻━━┻━━┛
commands:
#Disabling means only the commands will not work
  disabled: 
    trueorfalse: false
    1: "spawn" 
    2: "hub" 
    3: "lobby" 
    4: "tpa" 
    5: "home"
#Enabled means all the other commands than this one won't work
  enabled: 
    trueorfalse: true
    1: "lf"
    2: "" 
    3: ""
    4: "" 
    5: ""

#               ╭━━━╮     ╭╮
#               ┃╭━╮┃    ╭╯╰╮
#               ┃┃ ┃┃╭━━╮╰╮╭╯╭╮╭━━╮╭━╮ ╭━━╮
#               ┃┃ ┃┃┃╭╮┃ ┃┃ ┣┫┃╭╮┃┃╭╮╮┃━━┫
#               ┃╰━╯┃┃╰╯┃ ┃╰╮┃┃┃╰╯┃┃┃┃┃┣━━┃
#               ╰━━━╯┃╭━╯ ╰━╯╰╯╰━━╯╰╯╰╯╰━━╯
#                    ┃┃
#                    ╰╯
options:
# Give a player a shield in offhand
  shield: false
# Heal a player on kill
  heal: true
# Give a player a golden apple on kill
  Gapple: true
# Give a player a bow when pvp enabled
  bow: true
 # Start pvp with 5 Golden Apples
  gapplestart: true
# Give a player a fishing rod when pvp enabled
  fishingrod: true
# Give a player 64 steaks
  steak: true
# Position of the diamond sword
  slot: 8
# Enable Action bar
  actionbar: true
# Enable sounds
  sound: true
# Enable Titles
  title: true
  
  
  
enabledworlds:
  world: "world"
  
  
#            ╔═══╗
#            ║╔═╗║
#            ║╚═╝║╔══╗╔═╗╔╗╔╗╔╗╔══╗╔══╗╔╗╔══╗╔═╗─╔══╗
#            ║╔══╝║║═╣║╔╝║╚╝║╠╣║══╣║══╣╠╣║╔╗║║╔╗╗║══╣
#            ║║   ║║═╣║║ ║║║║║║╠══║╠══║║║║╚╝║║║║║╠══║
#            ╚╝   ╚══╝╚╝ ╚╩╩╝╚╝╚══╝╚══╝╚╝╚══╝╚╝╚╝╚══╝

#                       lf.reload


#                              ████████████████████████████████████████
#                              ██████▀░░░░░░░░▀████████▀▀░░░░░░░▀██████
#                              ████▀░░░░░░░░░░░░▀████▀░░░░░░░░░░░░▀████
#                              ██▀░░░░░░░░░░░░░░░░▀▀░░░░░░░░░░░░░░░░▀██
#                              ██░░░░░░░░░░░░░░░░░░░▄▄░░░░░░░░░░░░░░░██
#                              ██░░░░░░░░░░░░░░░░░▄▀░█░░░░░░░░░░░░░░░██    
#                              ██░░░░░░░░░░████▄▄▄▀░░▀▀▀▀▄░░░░░░░░░░░██
#                              ██▄░░░░░░░░░████░░░░░░░░░░█░░░░░░░░░░▄██
#                              ████▄░░░░░░░████░░░░░░░░░░█░░░░░░░░▄████
#                              ██████▄░░░░░████▄▄▄░░░░░░░█░░░░░░▄██████
#                              ████████▄░░░▀▀▀▀░░░▀▀▀▀▀▀▀░░░░░▄████████
#                              ██████████▄░░░░░░░░░░░░░░░░░░▄██████████
#                              ████████████▄░░░░░░░░░░░░░░▄████████████
#                              ██████████████▄░░░░░░░░░░▄██████████████
#                              ████████████████▄░░░░░░▄████████████████
#                              ██████████████████▄▄▄▄██████████████████
#
#██╗░░░░░███████╗░█████╗░██╗░░░██╗███████╗  ░█████╗░  ██████╗░███████╗██╗░░░██╗██╗███████╗░██╗░░░░░░░██╗                                                                                                          
#██║░░░░░██╔════╝██╔══██╗██║░░░██║██╔════╝  ██╔══██╗  ██╔══██╗██╔════╝██║░░░██║██║██╔════╝░██║░░██╗░░██║            
#██║░░░░░█████╗░░███████║╚██╗░██╔╝█████╗░░  ███████║  ██████╔╝█████╗░░╚██╗░██╔╝██║█████╗░░░╚██╗████╗██╔╝            
#██║░░░░░██╔══╝░░██╔══██║░╚████╔╝░██╔══╝░░  ██╔══██║  ██╔══██╗██╔══╝░░░╚████╔╝░██║██╔══╝░░░░████╔═████║░
#███████╗███████╗██║░░██║░░╚██╔╝░░███████╗  ██║░░██║  ██║░░██║███████╗░░╚██╔╝░░██║███████╗░░╚██╔╝░╚██╔╝░   
#╚══════╝╚══════╝╚═╝░░╚═╝░░░╚═╝░░░╚══════╝  ╚═╝░░╚═╝  ╚═╝░░╚═╝╚══════╝░░░╚═╝░░░╚═╝╚══════╝░░░╚═╝░░░╚═╝░░

#                  ░█████╗░███╗░░██╗  ░██████╗██████╗░██╗░██████╗░░█████╗░████████╗
#                  ██╔══██╗████╗░██║  ██╔════╝██╔══██╗██║██╔════╝░██╔══██╗╚══██╔══╝
#                  ██║░░██║██╔██╗██║  ╚█████╗░██████╔╝██║██║░░██╗░██║░░██║░░░██║░░░
#                  ██║░░██║██║╚████║  ░╚═══██╗██╔═══╝░██║██║░░╚██╗██║░░██║░░░██║░░░
#                  ╚█████╔╝██║░╚███║  ██████╔╝██║░░░░░██║╚██████╔╝╚█████╔╝░░░██║░░░
#                  ░╚════╝░╚═╝░░╚══╝  ╚═════╝░╚═╝░░░░░╚═╝░╚═════╝░░╚════╝░░░░╚═╝░░░                                                                                                             
#

